// Player skin registry: every visual component of a soldier is picked
// independently. Shared by client (rendering, picker) and server
// (validation, bot outfits). Easter-egg skins stay locked to their names;
// future skins can gate on lifetime kills via `milestoneKills`.

import { SKIN_MANIFEST } from './skins-manifest.ts';

export type SkinComponent = 'torso' | 'helmet' | 'legs' | 'pack' | 'gun' | 'head';

export interface Equip {
  torso: string;
  helmet: string;
  legs: string;
  pack: string;
  head: string;              // '' = classic painted head
}

export interface SkinDef {
  id: string;
  kind: SkinComponent;
  name: string;
  // base camo index (0..11), or a special paint the renderer understands
  paint: number | 'pink' | 'silver' | 'gold' | 'floral' | string;
  file?: string;             // baked AI component under /skins/ (webp)
  lockedTo?: string[];       // case-insensitive name substrings that may wear it
  milestoneKills?: number;   // future: lifetime kills required to unlock
}

const CAMO_NAMES = [
  'WOODLAND', 'DESERT', 'NIGHT OPS', 'URBAN', 'JUNGLE', 'ARID',
  'TAIGA', 'ASH', 'BRUSH', 'DUSK', 'STEPPE', 'MARSH',
];

// parametric recolors — [hue, sat, light] fed to the camo generator
export const RECOLOR_PAINTS: Record<string, [number, number, number]> = {
  ember: [18, 65, 34],
  frost: [205, 45, 52],
  jade: [150, 55, 30],
  royal: [268, 50, 36],
};

function camoSet(kind: SkinComponent, prefix: string): SkinDef[] {
  const out: SkinDef[] = CAMO_NAMES.map((name, i) => ({
    id: `${prefix}${i}`, kind, name, paint: i,
  }));
  for (const [key] of Object.entries(RECOLOR_PAINTS)) {
    out.push({ id: `${prefix}_${key}`, kind, name: key.toUpperCase(), paint: key });
  }
  return out;
}

const LOCK_SILVER = ['mutant', 'smock', 'mk47'];
const LOCK_PINK = ['darken'];
const LOCK_GOLD = ['tankarama'];
const LOCK_TEDGEY = ['tedgey'];
// names that see ONLY their own locked wardrobe (no standard 10)
const SOLE_NAMES = ['darken'];

// ---- baked AI components (webp cells under /skins/, shipped at 3 px/unit) ----
// The exact set is generated by ~/skin-assets/bake-ship.py after culling, so
// the picker only ever offers what actually shipped. To cull: rate an option
// below 4 (or "never") on skins.mynet.lol, then re-run bake-ship.py.
// pink/silver/gold suffixes on any component id map to their name lock
function colourLock(id: string): string[] | undefined {
  if (id.endsWith('pink') || id === 'darken') return LOCK_PINK;
  if (id.endsWith('silver')) return LOCK_SILVER;
  if (id.endsWith('gold')) return LOCK_GOLD;
  return undefined;
}

const aiHeads: SkinDef[] = SKIN_MANIFEST.heads.map((id) => ({
  id, kind: 'head', paint: 'ai', file: `heads/${id}.webp`,
  name: id === 'darken' ? 'THE DON' : `${id[0] === 'f' ? 'FEMALE' : 'MALE'} ${id.slice(1).toUpperCase()}`,
  ...(colourLock(id) ? { lockedTo: colourLock(id) } : {}),
}));

const HELM_LOCK: Record<string, string[]> = {
  floralblue: LOCK_TEDGEY, gold: LOCK_GOLD, pink: LOCK_PINK, silver: LOCK_SILVER,
};
const aiHelmets: SkinDef[] = SKIN_MANIFEST.helmets.map((n) => ({
  id: `k_${n}`, kind: 'helmet', name: n.toUpperCase(), paint: 'ai',
  file: `helmets/${n}.webp`,
  ...(HELM_LOCK[n] ? { lockedTo: HELM_LOCK[n] } : {}),
}));

const aiVests: SkinDef[] = SKIN_MANIFEST.vests.map((n, i) => ({
  id: `v_${n}`, kind: 'torso', name: `VEST ${i + 1}`, paint: 'ai',
  file: `vests/${n}.webp`,
  ...(n === 'pink_darken' ? { lockedTo: LOCK_PINK }
    : n === 'silver_smock' ? { lockedTo: LOCK_SILVER }
    : n === 'gold_tankarama' ? { lockedTo: LOCK_GOLD } : {}),
}));

const aiLegs: SkinDef[] = SKIN_MANIFEST.legs.map((id, i) => ({
  id, kind: 'legs', name: `LEGS ${i + 1}`, paint: 'ai', file: `legs/${id}.webp`,
  ...(colourLock(id) ? { lockedTo: colourLock(id) } : {}),
}));
const aiPacks: SkinDef[] = SKIN_MANIFEST.packs.map((id, i) => ({
  id, kind: 'pack', name: `JETPACK ${i + 1}`, paint: 'ai', file: `packs/${id}.webp`,
  ...(colourLock(id) ? { lockedTo: colourLock(id) } : {}),
}));

export const SKINS: SkinDef[] = [
  // legacy painted camo kept for back-compat validation of old saves; NOT
  // offered in the picker any more (see skinsFor) — the AI wardrobe replaces it
  ...camoSet('torso', 't'),
  { id: 'tp', kind: 'torso', name: 'HOT PINK', paint: 'pink', lockedTo: LOCK_PINK },
  { id: 'ts', kind: 'torso', name: 'CHROME', paint: 'silver', lockedTo: LOCK_SILVER },
  ...camoSet('legs', 'l'),
  { id: 'lp', kind: 'legs', name: 'HOT PINK', paint: 'pink', lockedTo: LOCK_PINK },
  { id: 'ls', kind: 'legs', name: 'CHROME', paint: 'silver', lockedTo: LOCK_SILVER },
  ...camoSet('pack', 'p'),
  { id: 'pp', kind: 'pack', name: 'HOT PINK', paint: 'pink', lockedTo: LOCK_PINK },
  ...camoSet('helmet', 'h'),
  { id: 'hg', kind: 'helmet', name: 'GOLD', paint: 'gold', lockedTo: ['tankarama'] },
  { id: 'hf', kind: 'helmet', name: 'FLORAL HAT', paint: 'floral', lockedTo: ['tedgey'] },
  { id: 'hs', kind: 'helmet', name: 'CHROME', paint: 'silver', lockedTo: LOCK_SILVER },
  // the shipped AI wardrobe (baked webp components under /skins/)
  ...aiVests,
  ...aiLegs,
  ...aiPacks,
  ...aiHelmets,
  ...aiHeads,
];

// does this outfit use any baked AI component?
export function equipUsesAi(eq: Equip): boolean {
  if (eq.head) return true;
  return (['torso', 'helmet', 'legs', 'pack'] as (keyof Equip)[])
    .some((f) => BY_ID.get(eq[f])?.file);
}

const BY_ID = new Map(SKINS.map((s) => [s.id, s]));

export function skinById(id: string): SkinDef | undefined {
  return BY_ID.get(id);
}

export function skinAllowed(def: SkinDef, playerName: string, lifetimeKills = 0): boolean {
  if (def.lockedTo && !def.lockedTo.some((t) => playerName.toLowerCase().includes(t))) return false;
  if (def.milestoneKills && lifetimeKills < def.milestoneKills) return false;
  return true;
}

// the picker (and bots) only ever see the shipped AI wardrobe now — the legacy
// painted camo stays in SKINS purely so old saved outfits still validate/render.
// SOLE names (darken) see ONLY their own locked wardrobe — no standard 10.
export function skinsFor(kind: SkinComponent, playerName: string, lifetimeKills = 0): SkinDef[] {
  const lower = playerName.toLowerCase();
  if (SOLE_NAMES.some((n) => lower.includes(n))) {
    return SKINS.filter((s) => s.kind === kind && s.file
      && s.lockedTo && s.lockedTo.some((t) => lower.includes(t)));
  }
  return SKINS.filter((s) => s.kind === kind && s.file && skinAllowed(s, playerName, lifetimeKills));
}

// the AI wardrobe a name wears when it never picked anything — a deterministic
// pick from the shipped components (name-hash), plus name-locked easter eggs
// the general (non-locked) pools each slot draws its default/random pick from
const OPEN_HEADS = aiHeads.filter((s) => !s.lockedTo).map((s) => s.id);
const OPEN_VESTS = aiVests.filter((s) => !s.lockedTo).map((s) => s.id);
const OPEN_HELMETS = aiHelmets.filter((s) => !s.lockedTo).map((s) => s.id);
const OPEN_LEGS = aiLegs.filter((s) => !s.lockedTo).map((s) => s.id);
const OPEN_PACKS = aiPacks.filter((s) => !s.lockedTo).map((s) => s.id);

// mutant/smock/mk47 carry an exclusive silver (chrome) gun, non-optional
export function hasSilverGun(name: string): boolean {
  const lower = name.toLowerCase();
  return LOCK_SILVER.some((t) => lower.includes(t));
}

// which gun-skin finish a player's weapon wears: name-locked gold/silver, else
// the weapon's featured default. The renderer falls back to the procedural gun
// when the chosen (weapon, variant) has no shipped skin.
export function gunVariantFor(name: string): 'gold' | 'silver' | 'def' {
  const lower = name.toLowerCase();
  if (LOCK_GOLD.some((t) => lower.includes(t))) return 'gold';
  if (LOCK_SILVER.some((t) => lower.includes(t))) return 'silver';
  return 'def';
}

// a random general face — for players/machines that never chose a head
export function randomHeadId(): string {
  return OPEN_HEADS[Math.floor(Math.random() * OPEN_HEADS.length)] ?? '';
}

export function defaultEquip(name: string): Equip {
  const lower = name.toLowerCase();
  let h = 0;
  for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) >>> 0;
  const at = (arr: readonly string[], shift: number): string => arr[(h >>> shift) % arr.length];
  // darken is fully exclusive — the whole pink outfit, no choices
  if (LOCK_PINK.some((t) => lower.includes(t))) {
    return { head: 'darken', helmet: 'k_pink', torso: 'v_pink_darken', legs: 'lg_pink', pack: 'jp_pink' };
  }
  const eq: Equip = {
    head: at(OPEN_HEADS, 0),
    torso: at(OPEN_VESTS, 4),
    helmet: at(OPEN_HELMETS, 8),
    legs: at(OPEN_LEGS, 12),
    pack: at(OPEN_PACKS, 16),
  };
  // mutant/tankarama keep the general head but default to their exclusive kit
  if (LOCK_SILVER.some((t) => lower.includes(t))) {
    eq.helmet = 'k_silver'; eq.torso = 'v_silver_smock'; eq.legs = 'lg_silver'; eq.pack = 'jp_silver';
  }
  if (lower.includes('tankarama')) {
    eq.helmet = 'k_gold'; eq.torso = 'v_gold_tankarama'; eq.legs = 'lg_gold'; eq.pack = 'jp_gold';
  }
  if (lower.includes('tedgey')) eq.helmet = 'k_floralblue';
  return eq;
}

// sanitize an equip request: unknown, wrong-kind, or locked picks fall back
export function validateEquip(raw: unknown, playerName: string, lifetimeKills = 0): Equip {
  const def = defaultEquip(playerName);
  if (typeof raw !== 'object' || raw === null) return def;
  const lower = playerName.toLowerCase();
  const sole = SOLE_NAMES.some((n) => lower.includes(n));
  const r = raw as Record<string, unknown>;
  // for sole names a pick must be one of their own locked pieces
  const ok = (s: SkinDef): boolean =>
    skinAllowed(s, playerName, lifetimeKills)
    && (!sole || (!!s.lockedTo && s.lockedTo.some((t) => lower.includes(t))));
  const pick = (field: keyof Equip, kind: SkinComponent): string => {
    const id = r[field];
    if (typeof id !== 'string') return def[field];
    const s = BY_ID.get(id);
    return s && s.kind === kind && ok(s) ? id : def[field];
  };
  let head = def.head;
  const rawHead = r['head'];
  if (typeof rawHead === 'string' && rawHead !== '') {
    const s = BY_ID.get(rawHead);
    if (s && s.kind === 'head' && ok(s)) head = rawHead;
  }
  return {
    torso: pick('torso', 'torso'),
    helmet: pick('helmet', 'helmet'),
    legs: pick('legs', 'legs'),
    pack: pick('pack', 'pack'),
    head,
  };
}
