// AUTO-GENERATED by ~/skin-assets/bake-ship.py — do not edit by hand.
// Cull options on skins.mynet.lol, then re-run bake-ship.py to update.
export const SKIN_MANIFEST = {
  "heads": [
    "f01",
    "f16",
    "f20",
    "fg01",
    "fg26",
    "m10",
    "m17",
    "m20",
    "mg03",
    "mg22",
    "darken"
  ],
  "helmets": [
    "campaign",
    "combat",
    "gold",
    "hh_g017",
    "hh_g028",
    "hh_g059",
    "hh_g071",
    "hh_g096",
    "para",
    "ranger",
    "ushanka",
    "pink",
    "silver",
    "floralblue"
  ],
  "vests": [
    "gold_tankarama",
    "pink_darken",
    "silver_smock",
    "sk100_vest_g023",
    "tnew_04",
    "tnew_05",
    "tnew_07",
    "tnew_18",
    "tnew_19",
    "tor_05_s0",
    "tor_20_s1",
    "tvar_04",
    "tvar_08"
  ],
  "legs": [
    "lg_00",
    "lg_01",
    "lg_02",
    "lg_07",
    "lg_11",
    "lg_g010",
    "lg_g028",
    "lg_g031",
    "lg_g046",
    "lg_g074",
    "lg_pink",
    "lg_silver",
    "lg_gold"
  ],
  "packs": [
    "jp_00",
    "jp_05",
    "jp_14",
    "jp_g005",
    "jp_g023",
    "jp_g038",
    "jp_g047",
    "jp_g073",
    "jp_g075",
    "jp_g080",
    "jp_pink",
    "jp_silver",
    "jp_gold"
  ],
  "guns": {
    "ak47": [
      "def",
      "gold",
      "silver"
    ],
    "dmr": [
      "def",
      "gold",
      "silver"
    ],
    "m249": [
      "def",
      "gold",
      "silver"
    ],
    "mac10": [
      "def",
      "gold",
      "silver"
    ],
    "mk47": [
      "gold",
      "silver"
    ],
    "mp5": [
      "def",
      "gold",
      "silver"
    ],
    "pan": [
      "def",
      "gold",
      "silver"
    ],
    "rifle": [
      "def",
      "gold",
      "silver"
    ],
    "shotgun": [
      "def",
      "gold",
      "silver"
    ],
    "sniper": [
      "def",
      "gold",
      "silver"
    ],
    "ump": [
      "def",
      "gold",
      "silver"
    ]
  }
} as const;
